### ISSUE TITLE
403: Forbidden

### ISSUE THREAD

**Issue by Pritesh1G** [amiechen/twitch-batch-loader#1]
![image](https://user-images.githubusercontent.com/18204740/39529680-e01f679e-4e44-11e8-93d8-6fa4b7c42e33.png)

**Comment by daevski** [comment]
I was also seeing this error. I've opened a pull request with a refresh of the script. I'm hoping it gets accepted because it uses "The New API" (Twitch's name for it) which is going to be the only API after the end of this year.

If you would like to pull my fork, I've verified lots of URLs work (every URL I've tried).

**Comment by amiechen** [comment]
the issue has been resolved by @daevski 's update
